# Generated by Django 5.1.1 on 2024-10-04 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0003_alter_usercustom_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustom',
            name='rol',
            field=models.CharField(blank=True, choices=[('user', 'user'), ('seller', 'seller'), ('admin', 'admin')], default='user', max_length=8),
        ),
    ]
